# 1. Main Portfolio (eslender.dev)
server {
    listen 80;
    server_name eslender.home www.eslender.home;

    location / {
        proxy_pass http://portfolio_app:3000;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
    }
}

# 2. Smart Desk Hub Showcase (hub.eslender.dev)
server {
    listen 80;
    server_name hub.eslender.dev;

    root /usr/share/nginx/html/hub;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }
}

# 3. Telemetry & Async WebSocket API (api.eslender.dev)
server {
    listen 80;
    server_name api.eslender.dev;

    location / {
        #proxy_pass http://hub_api:3000;
        #proxy_http_version 1.1;
        return 502;
        # Enable WebSocket upgrades
        #proxy_set_header Upgrade $http_upgrade;
        #proxy_set_header Connection "upgrade";
        #proxy_set_header Host $host;
        #proxy_cache_bypass $http_upgrade;
    }
}
