[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino

; Serial Monitor & Upload Configuration
upload_port = /dev/cu.usbserial-5B510100861
monitor_port = /dev/cu.usbserial-5B510100861
upload_speed = 115200      ; Prevents the flash chip connection error
monitor_speed = 115200

; Automatically fetches and manages libraries
lib_deps = 
    knolleary/PubSubClient @ ^2.8
    bblanchon/ArduinoJson @ ^6.21.3