[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino

build_flags = -DCORE_DEBUG_LEVEL=5

; Serial Monitor & Upload Configuration
upload_port = /dev/cu.usbserial-5B510100861
monitor_port = /dev/cu.usbserial-5B510100861
upload_speed = 115200      ; Prevents the flash chip connection error
monitor_speed = 115200

; Automatically fetches and manages libraries
lib_deps = 
    knolleary/PubSubClient @ ^2.8
    bblanchon/ArduinoJson @ ^6.21.3
    adafruit/Adafruit SSD1306 @ ^2.5.7       # OLED Display graphics
    adafruit/Adafruit GFX Library @ ^1.11.3  # Base graphics engine
    gilmaimon/ArduinoWebsockets @ ^0.5.3     # To stream audio to hub_api

    